### PR TITLE
Automatic versioning

### PR DESCRIPTION
**Pull request by MBeijer**
automatically updates build-date + version with the mkapollo.sh script

### CODE REVIEW

**Comment by MBeijer** [comment]
I'll make sure these changes works with the old "rebuild" scripts before it's time to merge it

**Comment by MBeijer** [comment]
Rebuild scripts should work now

**Comment by MBeijer** [comment]
Fixed conflicts @ronybeck

**Comment by MBeijer** [comment]
@JuanDoble07

**Review by JuanDoble07 — APPROVED** [review]
all good !!!

**Pull request merged**
