### PR TITLE
Update config.guess to version from automake 1.16.

### PR DESCRIPTION
**Pull request by AlbertoGP**
My system was not detected correctly with the old version of `config.guess` so I’ve updated all instances with a copy from `automake v1.16.3` without any modifications:
https://git.savannah.gnu.org/cgit/automake.git/tree/lib/config.guess?h=v1.16.3

### CODE REVIEW

**Comment by ronybeck** [comment]
Because I am not affected by this problem at all, could you give more details as to why this is a necessary change in the repo and not just something needed to be done on your system?   I don't have any context of this issue sorry.

**Comment by AlbertoGP** [comment]
The file `config.guess`’s function is to “[*Attempt to guess a canonical system name.*](https://git.savannah.gnu.org/cgit/automake.git/tree/lib/config.guess?h=v1.16.3)”, for instance `x86_64-pc-linux-gnu` for a Linux system running on an Intel Xeon CPU.
It can only guess correctly for some platforms. Over time, new checks are added to it to detect more.

Normally, using a newer version just means that potentially more platforms can be identified, without affecting those that were already working. I suppose they do drop obsolete platforms over time.

In my case, this is a Linux machine with an IBM Power9 CPU: `powerpc64le-unknown-linux-gnu`. Not mainstream, but not crazy rare either: this is still the current generation (Power10 will be released this year) and they are being sold new today.

Having updated copies of `config.guess` helps people like me, without harming those using more mainstream machines.

**Comment by AlbertoGP** [comment]
More context:
> You need to add the GNU config.guess and config.sub files to your distribution. They are needed because the AM_ICONV macro contains knowledge about specific platforms and therefore needs to identify the platform.
> You can obtain the newest version of config.guess and config.sub from the ‘config’ project at https://savannah.gnu.org/. The commands to fetch them are
> ``` $ wget -O config.guess 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'```
> ``` $ wget -O config.sub 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'```
> Less recent versions are also contained in the GNU automake and GNU libtool packages.
> Normally, config.guess and config.sub are put at the top level of a distribution. But it is also possible to put them in a subdirectory, altogether with other configuration support files like install-sh, ltconfig, ltmain.sh or missing. All you need to do, other than moving the files, is to add the following line to your configure.ac.
> `AC_CONFIG_AUX_DIR([subdir])`
https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html

Manual page: https://linux.die.net/man/1/config.guess

From reading that, I think I should also update `config.sub`.  Just updating `config.guess` was enough in my case.

**Comment by AlbertoGP** [comment]
Actually, we should update the to the latest version that does “update AROS system detection”:
https://git.savannah.gnu.org/cgit/config.git/commit/?id=6faca61810d335c7837f320733fe8e15a1431fc2

**Comment by AlbertoGP** [comment]
Ah, all right: turns out that there are no changes to `config.sub`, and the version of `config.guess` I had added is still the latest.
I’ve also rebased on the latest commits to `master-new` from [ApolloTeam-dev/AROS](https://github.com/ApolloTeam-dev/AROS) just in case, but it does not make a difference.

**Comment by MBeijer** [comment]
@ronybeck @AlbertoGP I'm pulling in this PR locally to test on my local machine, if this causes any issues:
**OS:** Debian GNU/Linux bullseye/sid x86_64 
**GCC:** gcc version 10.2.1 20210110 (Debian 10.2.1-6)
**AutoMake:** automake (GNU automake) 1.16.3

**Comment by MBeijer** [comment]
@AlbertoGP Could this cause issues with older versions of AutoMake?

**Comment by MBeijer** [comment]
The updated config.guess files seems to break the build. Doing some more tests to make sure.

**Comment by AlbertoGP** [comment]
Oh, I was just writing that I did not expect it to cause any trouble because it is not a library, but a standalone shell script that produces a short string as output. Being so loosely coupled I thought it would be fine.

In that case we can leave this open for other people to find if they have issues compiling on other machines.
It does not involve changes that would become more difficult to track over time, but plain whole file replacement.

**Comment by MBeijer** [comment]
could you pull in the latest changes from master to your branch so the Github workflow gets triggered?

**Comment by MBeijer** [comment]
Just want to make sure it's not something on my end messing things up

**Comment by MBeijer** [comment]
Hmm, issue seems to be on my end. Can't even compile master anymore :/

**Review by MBeijer — APPROVED** [review]
@AlbertoGP @ronybeck with a fresh clone of the branch I had no issues compiling with these changes

**Pull request closed without merging**
